version: "3.5"

services:
  api:
    image: bref/php-82-fpm-dev:2
    ports: ['8000:8000']
    volumes:
      - .:/var/task
    environment:
      HANDLER: htdocs/index.php
      # Assets will be served from this directory
      DOCUMENT_ROOT: htdocs
      PHP_INI_SCAN_DIR: /var/task/config/php